### ISSUE TITLE
有些书会因为图片404导致下载失败

### ISSUE THREAD

**Issue by Konecho** [VeronicaAlexia/HedgehogCatAppNovelDownload#11]
比如id为`100058816`的书，`Epub.py`文件`HTMLImage`类的`download_image`函数，无论尝试几次都会终止于请求`https://c1.kuangxiangit.com/uploads/chapterimgsnew/624/28272/180312/030526-15998.jpg`，并非网络问题，浏览器同样打不开，这类错误我尝试了300本老书有6本出现同样情况

ps：还有一次也是链接错误，src链接甚至是`file://C:UsersAdministratorDocumentsTencent Files【这里大概是作者qq号，码掉】ImageGroupImage5[@IT3JD$(TFVGC1CX}[W9Q4.jpg`

**Comment by VeronicaAlexia** [comment]
已经修复

**Comment by Konecho** [comment]
> 已经修复

感谢（我重新下载才发现实际404的图片链接太多了，全被我循环里的try给跳过了

**Comment by VeronicaAlexia** [comment]
不建议一次性大量下载书籍，很可能会触发刺猬猫封号机制。
