### ISSUE TITLE
[BUG] 部分书籍下载失败

### ISSUE THREAD

**Issue by name8102** [VeronicaAlexia/HedgehogCatAppNovelDownload#14]
```
[info] book-name:兄长大人的镇守府
[info] author-name:  战场原中喵
[info] book-id: 100047433
[info] new chapter: 第两千九百零四章  罪魁祸首竟是我自己
[info] last update: 2023-05-10 05:11:51
[info] book-cover-url: http://c1.kuangxiangit.com/uploads/allimg/c171109/09-11-17161546-49563-100047433.jpg
第1卷: 成为提督
第2卷: 学园
第3卷: 镇守府
第4卷: 秋季断代
第5卷: 意大利面条
第6卷: 发光的舰娘

[提示]本书一共有 14 章被屏蔽

[提示]最新章节: 第两千九百零四章  罪魁祸首竟是我自己    更新时间: 2023-05-10 05:11:51
length: 6 Loading... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━  95% 0:00:02                             
retries get with url: https://app.happybooker.cn/chapter/get_chapter_command retry: 4
length: 6 Loading... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━  95% 0:00:02
Max retries exceeded with url:https://app.happybooker.cn/chapter/get_chapter_command
```
比如说这个，可能是字数太多或者章节太多，有 3070 章 932.2 万字

另外这本书手机上能看网页看不了，刺猬猫迷之审核

**Comment by VeronicaAlexia** [comment]
> ```
> [info] book-name:兄长大人的镇守府
> [info] author-name:  战场原中喵
> [info] book-id: 100047433
> [info] new chapter: 第两千九百零四章  罪魁祸首竟是我自己
> [info] last update: 2023-05-10 05:11:51
> [info] book-cover-url: http://c1.kuangxiangit.com/uploads/allimg/c171109/09-11-17161546-49563-100047433.jpg
> 第1卷: 成为提督
> 第2卷: 学园
> 第3卷: 镇守府
> 第4卷: 秋季断代
> 第5卷: 意大利面条
> 第6卷: 发光的舰娘
> 
> [提示]本书一共有 14 章被屏蔽
> 
> [提示]最新章节: 第两千九百零四章  罪魁祸首竟是我自己    更新时间: 2023-05-10 05:11:51
> length: 6 Loading... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━  95% 0:00:02                             
> retries get with url: https://app.happybooker.cn/chapter/get_chapter_command retry: 4
> length: 6 Loading... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━  95% 0:00:02
> Max retries exceeded with url:https://app.happybooker.cn/chapter/get_chapter_command
> ```
> 
> 比如说这个，可能是字数太多或者章节太多，有 3070 章 932.2 万字
> 
> 另外这本书手机上能看网页看不了，刺猬猫迷之审核
https://github.com/VeronicaAlexia/HedgehogCatAppNovelDownload/blob/5577add361bee79cb699032f8c9fd064c4652358/HbookerAPI/HttpUtil.py#L26
https://github.com/VeronicaAlexia/HedgehogCatAppNovelDownload/blob/5577add361bee79cb699032f8c9fd064c4652358/HbookerAPI/HttpUtil.py#L40

Max retries exceeded with url:https://app.happybooker.cn/chapter/get_chapter_command
说明了同一个请求重试多次,触发到了重试上限,quit()强制关闭解释器并退出环境,你可以修改quit(...)t为print(...)

**Comment by VeronicaAlexia** [comment]
如果你觉得上述办法可以解决问题的话,我将关闭这个issues,如果不行可以继续提问
