### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by qazmko1029** [VeronicaAlexia/HedgehogCatAppNovelDownload#15]
config.json填了login_token和account，运行python3 run.py在HbookerAPI.SignUp.user_account()没过，循环提示：
Error: 登录状态过期2，请重新登录 请先登入账号！
[warn]hbooker api test account is invalid, test your config.json information

**Comment by VeronicaAlexia** [comment]
是否肯定login_token没有过期?login_token每一次登入获取新的login_token后,其它旧的login_token会失效

**Comment by qazmko1029** [comment]
是昨天刚抓手机包获得的login_token，不太可能马上过期的
