### ISSUE TITLE
用户名无法读取 ，显示为None

### ISSUE THREAD

**Issue by clsy-xa01** [VeronicaAlexia/HedgehogCatAppNovelDownload#18]
我通过浏览器获取到login_token,然后account我填了app里的账户名“书客xxxxxx”
报错为
Error: 网络出错，请重试或重新登录 请先登入账号！
[warn]hbooker api test account is invalid, test your config.json information

**Comment by clsy-xa01** [comment]
单独输入 python run.py进去，login xx xx也不行

**Comment by AlexiaAshford** [comment]
并不是浏览器的token，是Android app的
