### ISSUE TITLE
这个该怎么提取出里面的东西

### ISSUE THREAD

**Issue by shiki-su** [VeronicaAlexia/HedgehogCatAppNovelDownload#6]
![Screenshot_20220610_194809](https://user-images.githubusercontent.com/107031856/173058335-4c1040b9-4c8f-4fc1-923a-da43bde34159.jpg)
可不可以改成txt然后直接复制里面的内容

**Comment by VeronicaAlexia** [comment]
> ![Screenshot_20220610_194809](https://user-images.githubusercontent.com/107031856/173058335-4c1040b9-4c8f-4fc1-923a-da43bde34159.jpg) 可不可以改成txt然后直接复制里面的内容

当然可以，我相信这是你的个人的权利和自由，你可以自由的尝试和复制内容

**Comment by liuzhenmin3** [comment]
请问这个文件是在哪里找到的
