### ISSUE TITLE
关于token的获取

### ISSUE THREAD

**Issue by liuzhenmin3** [VeronicaAlexia/HedgehogCatAppNovelDownload#7]
能否请您将从正确的token和account获取的流程为我讲解一下，我的相关知识较为匮乏。十分感谢！邮箱：liuzhenmin3@qq.com

**Comment by VeronicaAlexia** [comment]
你可以尝试抓包或者本地获取

**Comment by liuzhenmin3** [comment]
请问本地的话是在哪个地址的哪个文件

**Comment by VeronicaAlexia** [comment]
> 请问本地的话是在哪个地址的哪个文件


com.kuangxiangciweimao.novel\shared_prefs\com.kuangxiangciweimao.novel_preferences.xml

**Comment by liuzhenmin3** [comment]
己找到，十分感谢
